### ISSUE TITLE
Apply Email

### ISSUE THREAD

**Issue by ghost** [proj-at/subdomains#2]
The prefix of your `@proj.sbs` email: `tcp@proj.sbs`

The forwarded address of your email: `contact.thecipherproject@gmail.com`

**Comment by ghost** [comment]
On the privacy side of this, will you be able to read/interact with any of the emails sent?

**Comment by ocoke** [comment]
I'm sorry. Actually, the email feature is based on Cloudflare Email Forwarding, so the email domain must be `@proj.sbs`, like `cky@proj.sbs`. This only supports receiving emails and I am not able to read them, it just forwards to your email. You are also not able to send email via this address.

**Comment by ghost** [comment]
oh right, let me edit it.

**Comment by ghost** [comment]
done!

**Comment by ghost** [comment]
btw @ocoke i’d be interested in becoming a member of proj-at if you are looking for people to help out

**Comment by ocoke** [comment]
ok, a verification email was sent to your email address by Cloudflare.

**Comment by ghost** [comment]
ok, it’s verified. thanks
