### ISSUE TITLE
too many redirects

### ISSUE THREAD

**Issue by ghost** [proj-at/subdomains#7]
my subdomain is getting a too many redirects error. is there an issue on your side?

**Comment by 4d62** [comment]
cc @ocoke

**Comment by ghost** [comment]
my index.html page contains one paragraph tab so i doubt it’s caused by that. here is what i see:
![IMG_1834](https://github.com/proj-at/subdomains/assets/141976171/7962ec87-676c-447f-9c8d-81587799f5f3)

**Comment by ghost** [comment]
this has been fixed. i removed all anchor tags on my index.html and redeployed

**Comment by ghost** [comment]
wait no nvm now the other pages are bugged.

**Comment by ghost** [comment]
looks mostly fine now. will close as resolved
