### ISSUE TITLE
Proj.at Domain

### ISSUE THREAD

**Issue by ghost** [proj-at/subdomains#9]
Hey there, do you know when we can register proj.at domains?

**Comment by AtlasL1** [comment]
Yeah, my name is Atlas and people call me At for short. Would be so cool if I got proj.at! (I'm broke)

**Comment by CarsonDay11** [comment]
proj.at is their personal domain?

**Comment by CarsonDay11** [comment]
I doubt they will offer subdomains for proj.at, since it is their personal domain.
